const chars=[
{id:'sugar',name:'각설탕',quote:'달지만 승부는 쓰다',color:0xf4edcf,css:'#f4edcf',w:54,h:54},
{id:'brown',name:'흑설탕',quote:'묵직하게 간다',color:0x8b5732,css:'#8b5732',w:54,h:54},
{id:'salt',name:'소금덩어리',quote:'지는 건 짜다',color:0xdaf4ff,css:'#daf4ff',w:54,h:54},
{id:'tofu',name:'두부',quote:'부서져도 달린다',color:0xffe8ae,css:'#ffe8ae',w:58,h:50},
{id:'brick',name:'벽돌',quote:'대화보다 돌진',color:0xb9513a,css:'#b9513a',w:66,h:48},
{id:'box',name:'택배상자',quote:'배송보다 빠르게',color:0xb9854d,css:'#b9854d',w:58,h:54},
{id:'apartment',name:'아파트',quote:'관리비 걸고 뛴다',color:0xb7a07d,css:'#b7a07d',w:50,h:76},
{id:'gold',name:'금괴',quote:'몸값부터 다름',color:0xe8bd31,css:'#e8bd31',w:66,h:44},
{id:'safe',name:'금고',quote:'마음은 잠금',color:0x6d7683,css:'#6d7683',w:58,h:58}
];
const diffs={
 easy:{label:'느긋',desc:'AI가 자주 실수',speed:.72,stumble:.085,reaction:[360,650],jump:[4.3,6.4]},
 normal:{label:'보통',desc:'기본 난이도',speed:.92,stumble:.052,reaction:[240,460],jump:[5.0,7.4]},
 hard:{label:'빡셈',desc:'실수하면 추월',speed:1.08,stumble:.03,reaction:[175,335],jump:[5.8,8.1]},
 hell:{label:'악마',desc:'거의 안 틀림',speed:1.23,stumble:.014,reaction:[135,265],jump:[6.4,8.6]}
};
const S={selected:'sugar',difficulty:'normal',event:'sprint',game:null,scene:null,sound:true,lastFoot:null,combo:0,power:0,locked:false,phase:'idle'};
const $=q=>document.querySelector(q), $$=q=>[...document.querySelectorAll(q)];
const me=()=>chars.find(c=>c.id===S.selected);
function showMsg(t,ms=800){const e=$('#overlayMessage');e.textContent=t;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),ms)}
function vibrate(p){if(navigator.vibrate)navigator.vibrate(p)}
let ac=null;function beep(f=440,d=.07,type='square',v=.03){if(!S.sound)return;try{ac=ac||new(window.AudioContext||window.webkitAudioContext)();const o=ac.createOscillator(),g=ac.createGain();o.frequency.value=f;o.type=type;g.gain.value=v;o.connect(g);g.connect(ac.destination);o.start();g.gain.exponentialRampToValueAtTime(.0001,ac.currentTime+d);o.stop(ac.currentTime+d)}catch(e){}}
function confetti(n=30){for(let i=0;i<n;i++){const x=document.createElement('i');x.className='confetti';x.style.left=Math.random()*100+'vw';x.style.background=`hsl(${Math.random()*360} 90% 60%)`;x.style.setProperty('--x',(-100+Math.random()*200)+'px');document.body.appendChild(x);setTimeout(()=>x.remove(),1700)}}
function renderHome(){
 $('#difficultyGrid').innerHTML=Object.entries(diffs).map(([k,d])=>`<button class="difficulty-btn ${S.difficulty===k?'selected':''}" data-d="${k}"><strong>${d.label}</strong><small>${d.desc}</small></button>`).join('');
 $$('.difficulty-btn').forEach(b=>b.onclick=()=>{S.difficulty=b.dataset.d;renderHome()});
 $('#charGrid').innerHTML=chars.map(c=>`<button class="char ${S.selected===c.id?'selected':''}" data-c="${c.id}"><div class="cube" style="background:${c.css}">•ᴗ•</div><strong>${c.name}</strong><small>${c.quote}</small></button>`).join('');
 $$('.char').forEach(b=>b.onclick=()=>{S.selected=b.dataset.c;renderHome()});
}
renderHome();
$('#soundBtn').onclick=()=>{S.sound=!S.sound;$('#soundBtn').textContent=S.sound?'🔊':'🔇'};
$$('.event').forEach(b=>b.onclick=()=>openGame(b.dataset.event));
$('#backBtn').onclick=goHome;$('#homeBtn').onclick=goHome;$('#retryBtn').onclick=()=>{hideResult();openGame(S.event)};
function goHome(){destroyGame();hideResult();$('#gameScreen').hidden=true;$('#homeScreen').hidden=false}
function destroyGame(){if(S.game){S.game.destroy(true);S.game=null;S.scene=null}$('#phaserMount').innerHTML=''}
function hideResult(){$('#resultPanel').hidden=true}
function setHud(l1,v1,l2,v2,bar=0){$('#hudLeftLabel').textContent=l1;$('#hudLeft').textContent=v1;$('#hudRightLabel').textContent=l2;$('#hudRight').textContent=v2;$('#hudBar').style.width=Math.max(0,Math.min(100,bar))+'%'}
function showResults(title,big,rows,win){$('#resultTitle').textContent=title;$('#recordBig').textContent=big;$('#resultList').innerHTML=rows.map((r,i)=>`<div class="result-row ${r.me?'me':''}"><span><strong>${i+1}위</strong> · ${r.name}</span><strong>${r.value}</strong></div>`).join('');$('#resultPanel').hidden=false;if(win){confetti();beep(820,.1);setTimeout(()=>beep(1040,.14),100)}}
function paintFoot(next){['leftBtn','rightBtn'].forEach(id=>$('#'+id)?.classList.remove('next'));if(next&&!S.locked)$('#'+(next==='L'?'leftBtn':'rightBtn'))?.classList.add('next')}
function setFeet(withJump=false){$('#controls').innerHTML=`<div class="foot-controls"><button id="leftBtn" class="tap">👈 왼발</button><button id="rightBtn" class="tap">오른발 👉</button></div>${withJump?'<button id="jumpBtn" class="jump-btn" disabled>구름판까지 달려!</button>':''}`;$('#leftBtn').onclick=()=>foot('L');$('#rightBtn').onclick=()=>foot('R');if(withJump)$('#jumpBtn').onclick=()=>S.scene?.takeoff();paintFoot('L')}
function foot(f){if(!S.scene||S.locked||!['run','approach'].includes(S.phase))return;if(S.lastFoot===f){S.scene.stumble?.();return}S.lastFoot=f;S.combo++;S.power=Math.min(100,S.power+5+Math.min(2.5,S.combo*.08));paintFoot(f==='L'?'R':'L');setHud('COMBO',S.combo,'SPEED',Math.round(S.power)+'%',S.power);S.scene.onStep?.(f)}
function makeNemo(scene,c,x,y,label){const ct=scene.add.container(x,y);const shadow=scene.add.ellipse(0,c.h*.58+13,c.w*.92,14,0x000000,.24);const body=scene.add.rectangle(0,0,c.w,c.h,c.color).setStrokeStyle(3,0xffffff,.42);const face=scene.add.text(0,-2,'•ᴗ•',{fontFamily:'Arial',fontSize:'17px',fontStyle:'bold',color:'#20242d'}).setOrigin(.5);const armL=scene.add.rectangle(-c.w/2-8,4,18,7,c.color),armR=scene.add.rectangle(c.w/2+8,4,18,7,c.color);const legL=scene.add.rectangle(-13,c.h/2+9,10,24,0x3b3030).setOrigin(.5,0),legR=scene.add.rectangle(13,c.h/2+9,10,24,0x3b3030).setOrigin(.5,0);ct.add([shadow,armL,armR,legL,legR,body,face]);ct.setData({face,armL,armR,legL,legR,baseY:y});if(label)ct.add(scene.add.text(0,-c.h/2-24,label,{fontFamily:'Arial',fontSize:'13px',fontStyle:'bold',color:'#fff',backgroundColor:'#111827dd',padding:{x:6,y:3}}).setOrigin(.5));return ct}
function runAnim(n,t,m=1){const d=n.getData(),s=Math.sin(t*.025*m);d.legL.rotation=s*.9;d.legR.rotation=-s*.9;d.armL.rotation=-s*.65;d.armR.rotation=s*.65;n.y=d.baseY+Math.abs(s)*3}
function stadium(scene){scene.cameras.main.setBackgroundColor('#73c9ff');scene.add.rectangle(500,94,1000,188,0x73c9ff);scene.add.rectangle(500,190,1000,62,0x253453);for(let x=8;x<1000;x+=17)scene.add.circle(x+Math.random()*7,174+Math.random()*32,3,[0xffd84d,0xff6c69,0x5ce6aa,0xffffff][Math.floor(Math.random()*4)],.78);scene.add.rectangle(500,226,1000,10,0xf6d79c)}
function openGame(type){destroyGame();hideResult();Object.assign(S,{event:type,lastFoot:null,combo:0,power:0,locked:false,phase:'idle'});$('#homeScreen').hidden=true;$('#gameScreen').hidden=false;const meta={sprint:['50m 달리기','왼발·오른발을 번갈아 눌러 결승선까지 달려!'],jump:['멀리뛰기','왼발·오른발로 도움닫기. 구름판 직전에 JUMP!'],reaction:['출발 반응 레이스','🔴 기다려! → 🟢 GO!가 켜지면 큰 버튼을 눌러 출발!']}[type];$('#gameTitle').textContent=meta[0];$('#hint').textContent=meta[1];$('#roundLabel').textContent=`AI ${diffs[S.difficulty].label} · PLAYTEST 0.5`;$('#timer').textContent='READY';const C=type==='sprint'?Sprint:type==='jump'?Jump:Reaction;S.game=new Phaser.Game({type:Phaser.AUTO,parent:'phaserMount',width:1000,height:620,backgroundColor:'#111827',scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH},scene:C})}
class Sprint extends Phaser.Scene{
 constructor(){super('Sprint')}
 create(){S.scene=this;S.phase='count';stadium(this);this.finishX=880;this.add.rectangle(500,430,1000,380,0xc55f42);for(let i=0;i<5;i++)this.add.rectangle(500,300+i*72,1000,2,0xffffff,.35);this.add.rectangle(this.finishX,430,14,380,0xffffff);for(let y=250;y<610;y+=22)this.add.rectangle(this.finishX,y,14,11,(y/22)%2?0x111111:0xffffff);this.runners=[];const others=chars.filter(c=>c.id!==S.selected).sort(()=>Math.random()-.5).slice(0,3),roster=[me(),...others];for(let i=0;i<4;i++){const n=makeNemo(this,roster[i],105,300+i*72,i===0?'나':['민수','지현','철수'][i-1]);this.runners.push({n,x:105,name:i===0?'나':['민수','지현','철수'][i-1],finish:null,rate:(.85+Math.random()*.16)*diffs[S.difficulty].speed})}setFeet();$('#leftBtn').disabled=$('#rightBtn').disabled=true;setHud('COMBO','0','SPEED','0%',0);let c=3;$('#timer').textContent='3';showMsg('3');beep(430);this.time.addEvent({delay:650,repeat:2,callback:()=>{c--;if(c>0){$('#timer').textContent=c;showMsg(String(c));beep(430)}else{S.phase='run';$('#timer').textContent='GO!';showMsg('GO! 달려!',650);beep(850,.1);vibrate(40);$('#leftBtn').disabled=$('#rightBtn').disabled=false;paintFoot('L')}}})}
 onStep(){const r=this.runners[0],step=24+S.power*.08+Math.min(5,S.combo*.1);r.x=Math.min(this.finishX,r.x+step);r.n.x=r.x;this.dust(r.x,r.n.y+35);if(r.x>=this.finishX)this.finish(0)}
 dust(x,y){const p=this.add.circle(x-25,y,5,0xe6c5a2,.7);this.tweens.add({targets:p,x:x-60,alpha:0,scale:1.8,duration:260,onComplete:()=>p.destroy()})}
 stumble(){if(S.locked)return;S.locked=true;S.combo=0;S.power=Math.max(0,S.power-30);setHud('COMBO','0','SPEED',Math.round(S.power)+'%',S.power);paintFoot(null);const n=this.runners[0].n;n.getData().face.setText('×﹏×');this.tweens.add({targets:n,angle:82,x:n.x-12,duration:150,yoyo:true});this.cameras.main.shake(160,.008);showMsg('발 꼬임! 🤦');beep(140,.12,'sawtooth');vibrate([30,25,60]);this.time.delayedCall(450,()=>{S.locked=false;S.lastFoot=null;n.angle=0;n.getData().face.setText('•ᴗ•');paintFoot('L')})}
 finish(i){const r=this.runners[i];if(r.finish)return;r.finish=this.time.now;if(i===0){S.phase='done';$('#leftBtn').disabled=$('#rightBtn').disabled=true;showMsg('FINISH!',650);vibrate([25,20,55]);this.time.delayedCall(650,()=>this.result())}}
 result(){const mt=this.runners[0].finish||this.time.now;this.runners.forEach(r=>{if(!r.finish)r.finish=mt+(this.finishX-r.x)*7});const sorted=[...this.runners].sort((a,b)=>a.finish-b.finish),rows=sorted.map(r=>({name:r.name,me:r.name==='나',value:(5+(r.finish-sorted[0].finish)*.001).toFixed(2)+'s'})),rank=sorted.findIndex(r=>r.name==='나')+1;showResults(rank===1?'🏆 스프린트 우승!':`${rank}위!`,rows.find(r=>r.me).value,rows,rank===1)}
 update(time){if(S.phase!=='run')return;this.runners.forEach((r,i)=>{runAnim(r.n,time,1.3+r.rate+S.power/130);if(i===0||r.finish)return;if(Math.random()<diffs[S.difficulty].stumble*.01){r.n.angle=55;this.time.delayedCall(130,()=>r.n.angle=0);return}r.x=Math.min(this.finishX,r.x+1.7+r.rate*2.1);r.n.x=r.x;if(r.x>=this.finishX)this.finish(i)})}
}
class Jump extends Phaser.Scene{
 constructor(){super('Jump')}
 create(){S.scene=this;S.phase='approach';stadium(this);this.runY=430;this.boardX=665;this.pitStart=695;this.add.rectangle(335,450,670,340,0xb95b40);this.add.rectangle(850,455,300,330,0xe5c17e);this.add.rectangle(this.boardX,430,18,80,0xffffff);this.add.rectangle(this.boardX+12,430,6,80,0xe54b4b);this.add.text(620,350,'구름판',{fontSize:'17px',fontStyle:'bold',color:'#fff'});this.add.text(790,355,'SAND PIT',{fontSize:'21px',fontStyle:'bold',color:'#80602f'});this.ai=this.makeAi();this.ai.forEach((v,i)=>{const x=Math.min(955,this.pitStart+v*34);this.add.rectangle(x,415,4,92,[0xff6570,0x5ce6aa,0xffd84d][i]);this.add.text(x-16,365,['민수','지현','철수'][i],{fontSize:'11px',color:'#263044'})});this.player=makeNemo(this,me(),105,this.runY,'나');setFeet(true);setHud('COMBO','0','SPEED','0%',0);$('#timer').textContent='RUN';$('#jumpBtn').disabled=true;showMsg('도움닫기 시작!');this.vx=0;this.vy=0}
 makeAi(){const [a,b]=diffs[S.difficulty].jump;return Array.from({length:3},()=>a+Math.random()*(b-a)).sort((a,b)=>b-a)}
 onStep(){if(S.phase!=='approach')return;const step=22+S.power*.075+Math.min(4,S.combo*.08);this.player.x+=step;const rem=this.boardX-this.player.x;$('#timer').textContent=rem>0?(rem/62).toFixed(1)+'m':'BOARD';if(rem<200){$('#jumpBtn').disabled=false;$('#jumpBtn').textContent=rem>85?'JUMP 준비!':rem>=-8?'🔥 지금 JUMP!':'늦었다!';if(rem<75&&rem>20)showMsg('지금! JUMP!',300)}if(this.player.x>this.boardX+14)this.foul()}
 stumble(){if(S.locked)return;S.locked=true;S.combo=0;S.power=Math.max(0,S.power-25);setHud('COMBO','0','SPEED',Math.round(S.power)+'%',S.power);paintFoot(null);this.player.getData().face.setText('×﹏×');this.tweens.add({targets:this.player,angle:72,x:this.player.x-10,duration:150,yoyo:true});showMsg('발 꼬임!');vibrate([30,25,55]);this.time.delayedCall(420,()=>{S.locked=false;S.lastFoot=null;this.player.angle=0;this.player.getData().face.setText('•ᴗ•');paintFoot('L')})}
 takeoff(){if(S.phase!=='approach')return;const err=this.boardX-this.player.x;if(err<-12){this.foul();return}S.phase='air';['leftBtn','rightBtn','jumpBtn'].forEach(id=>$('#'+id).disabled=true);const perfect=Math.abs(err)<=18,accuracy=Math.max(.76,1-Math.max(0,err-5)/260);this.vx=(360+S.power*2.5)*accuracy;this.vy=-(560+S.power*1.55);this.player.getData().face.setText('•O•');$('#timer').textContent=perfect?'PERFECT':'AIR';showMsg(perfect?'PERFECT TAKEOFF! 🔥':'날아간다!',700);if(perfect)vibrate([20,20,35])}
 foul(){if(['foul','done'].includes(S.phase))return;S.phase='foul';['leftBtn','rightBtn','jumpBtn'].forEach(id=>{if($('#'+id))$('#'+id).disabled=true});this.player.getData().face.setText('×﹏×');$('#timer').textContent='FOUL';showMsg('FOUL! 😵',850);vibrate([65,35,65]);this.time.delayedCall(800,()=>this.finish(true))}
 finish(foul=false){if(S.phase==='done')return;S.phase='done';const rec=foul?0:Math.min(9.5,Math.max(0,(this.player.x-this.boardX)/34));const all=[{name:'나',me:true,score:rec,foul},...this.ai.map((v,i)=>({name:['민수','지현','철수'][i],me:false,score:v,foul:false}))].sort((a,b)=>b.score-a.score),rows=all.map(r=>({name:r.name,me:r.me,value:r.foul?'FOUL':r.score.toFixed(2)+'m'})),rank=all.findIndex(r=>r.me)+1;showResults(foul?'😵 파울!':rank===1?'🏆 멀리뛰기 우승!':`${rank}위!`,foul?'FOUL':rec.toFixed(2)+'m',rows,rank===1&&!foul)}
 update(time,delta){if(S.phase==='approach')runAnim(this.player,time,1.2+S.power/60);if(S.phase==='air'){const dt=delta/1000;this.player.x+=this.vx*dt;this.player.y+=this.vy*dt;this.vy+=1120*dt;this.player.angle+=125*dt;$('#timer').textContent=Math.max(0,(this.player.x-this.boardX)/34).toFixed(2)+'m';if(this.player.y>=this.runY+38&&this.player.x>this.pitStart){this.player.y=this.runY+38;this.player.angle=0;this.player.getData().face.setText('×ᴗ×');S.phase='land';showMsg('푹! 착지!',600);this.cameras.main.shake(180,.006);vibrate([35,20,50]);for(let i=0;i<18;i++){const p=this.add.circle(this.player.x-10+Math.random()*40,this.player.y+18,3+Math.random()*5,0xd0a761,.85);this.tweens.add({targets:p,x:p.x-55+Math.random()*110,y:p.y-20-Math.random()*65,alpha:0,duration:520,onComplete:()=>p.destroy()})}this.tweens.add({targets:this.player,x:this.player.x+30,angle:55,duration:230,yoyo:true,onComplete:()=>{this.player.angle=0;this.finish(false)}})}}}
}
class Reaction extends Phaser.Scene{
 constructor(){super('Reaction')}
 create(){S.scene=this;S.phase='red';stadium(this);this.finishX=840;this.add.rectangle(500,440,1000,360,0xc45e40);for(let i=0;i<5;i++)this.add.rectangle(500,315+i*70,1000,2,0xffffff,.32);this.add.rectangle(this.finishX,440,12,350,0xffffff);const others=chars.filter(c=>c.id!==S.selected).sort(()=>Math.random()-.5).slice(0,3),roster=[me(),...others];this.runners=roster.map((c,i)=>({n:makeNemo(this,c,155,315+i*70,i===0?'나':['민수','지현','철수'][i-1]),name:i===0?'나':['민수','지현','철수'][i-1],reaction:null,x:155,started:false,finish:null}));$('#controls').innerHTML='<div class="traffic"><i id="redLight" class="light red on"></i><i id="greenLight" class="light green"></i></div><button id="reactionBtn" class="reaction-button">🔴 기다려!</button>';setHud('상태','대기','AI',diffs[S.difficulty].label,0);$('#timer').textContent='RED';$('#reactionBtn').onclick=()=>this.press();showMsg('빨간불엔 누르지 마!',1000);const wait=1700+Math.random()*2200;this.time.delayedCall(wait,()=>this.go())}
 go(){if(S.phase!=='red')return;S.phase='green';this.goAt=performance.now();$('#redLight').classList.remove('on');$('#greenLight').classList.add('on');const b=$('#reactionBtn');b.textContent='🟢 GO! 지금 눌러!';b.classList.add('go');$('#timer').textContent='GO!';setHud('상태','GO!','AI',diffs[S.difficulty].label,0);showMsg('GO!!!',450);beep(950,.08);vibrate(30);const [lo,hi]=diffs[S.difficulty].reaction;this.runners.slice(1).forEach(r=>{r.reaction=lo+Math.random()*(hi-lo);this.time.delayedCall(r.reaction,()=>{r.started=true})})}
 press(){const b=$('#reactionBtn');if(S.phase==='red'){S.phase='false';this.runners[0].reaction=9999;b.textContent='부정출발!';b.classList.add('false');$('#timer').textContent='FALSE';showMsg('너무 빨랐다! 😵',800);vibrate([70,40,70]);const [lo,hi]=diffs[S.difficulty].reaction;this.runners.slice(1).forEach(r=>{r.reaction=lo+Math.random()*(hi-lo);r.started=true});this.time.delayedCall(850,()=>this.result())}else if(S.phase==='green'){S.phase='race';this.runners[0].reaction=performance.now()-this.goAt;this.runners[0].started=true;b.textContent=Math.round(this.runners[0].reaction)+'ms · 달린다!';setHud('반응',Math.round(this.runners[0].reaction)+'ms','레이스','진행 중',0)}}
 result(){const all=[...this.runners].sort((a,b)=>a.reaction-b.reaction),rows=all.map(r=>({name:r.name,me:r.name==='나',value:r.reaction>9000?'실격':Math.round(r.reaction)+'ms'})),rank=all.findIndex(r=>r.name==='나')+1;showResults(this.runners[0].reaction>9000?'😵 부정출발!':rank===1?'⚡ 출발 반응 1등!':`${rank}위!`,this.runners[0].reaction>9000?'FALSE':Math.round(this.runners[0].reaction)+'ms',rows,rank===1)}
 update(time){if(!['green','race'].includes(S.phase))return;this.runners.forEach((r,i)=>{if(!r.started||r.finish)return;runAnim(r.n,time,1.5);r.x+=i===0?4.6:4.15+diffs[S.difficulty].speed*.55;r.n.x=r.x;if(r.x>=this.finishX)r.finish=this.time.now});if(S.phase==='race'&&this.runners[0].finish){S.phase='done';showMsg('FINISH!',500);this.time.delayedCall(500,()=>this.result())}}
}
