const chars=[
{id:'sugar',name:'각설탕',quote:'달지만 승부는 쓰다',color:0xf4edcf,css:'#f4edcf',w:48,h:48},
{id:'brown',name:'흑설탕',quote:'묵직하게 간다',color:0x8b5732,css:'#8b5732',w:48,h:48},
{id:'salt',name:'소금덩어리',quote:'지는 건 짜다',color:0xdaf4ff,css:'#daf4ff',w:48,h:48},
{id:'tofu',name:'두부',quote:'부서져도 달린다',color:0xffe8ae,css:'#ffe8ae',w:50,h:44},
{id:'brick',name:'벽돌',quote:'대화보다 돌진',color:0xb9513a,css:'#b9513a',w:58,h:42},
{id:'box',name:'택배상자',quote:'배송보다 빠르게',color:0xb9854d,css:'#b9854d',w:52,h:48},
{id:'apartment',name:'아파트',quote:'관리비 걸고 뛴다',color:0xb7a07d,css:'#b7a07d',w:44,h:66},
{id:'gold',name:'금괴',quote:'몸값부터 다름',color:0xe8bd31,css:'#e8bd31',w:58,h:38},
{id:'safe',name:'금고',quote:'마음은 잠금',color:0x6d7683,css:'#6d7683',w:50,h:50}
];
const diffs={
 easy:{label:'느긋',desc:'AI도 자주 삐끗',bot:0.73,stumble:.10,reaction:[330,610],jump:[4.5,6.7]},
 normal:{label:'보통',desc:'한 판 붙기 좋음',bot:0.90,stumble:.065,reaction:[230,450],jump:[5.2,7.4]},
 hard:{label:'빡셈',desc:'리듬 놓치면 추월',bot:1.05,stumble:.038,reaction:[175,330],jump:[5.8,8.0]},
 hell:{label:'악마',desc:'벽돌도 날아다님',bot:1.18,stumble:.018,reaction:[135,260],jump:[6.4,8.45]}
};
const S={selected:'sugar',difficulty:'normal',event:'jump',game:null,scene:null,sound:true,lastFoot:null,combo:0,power:0,locked:false,phase:'idle',results:[]};
const $=q=>document.querySelector(q), $$=q=>[...document.querySelectorAll(q)];
function ch(){return chars.find(c=>c.id===S.selected)}
function vibrate(p){if(navigator.vibrate)navigator.vibrate(p)}
let actx=null;function beep(f=440,d=.07,type='square',v=.03){if(!S.sound)return;try{actx=actx||new(window.AudioContext||window.webkitAudioContext)();const o=actx.createOscillator(),g=actx.createGain();o.frequency.value=f;o.type=type;g.gain.value=v;o.connect(g);g.connect(actx.destination);o.start();g.gain.exponentialRampToValueAtTime(.0001,actx.currentTime+d);o.stop(actx.currentTime+d)}catch(e){}}
function call(text,ms=800){const el=$('#gameCall');el.textContent=text;el.classList.add('show');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.remove('show'),ms)}
function confetti(n=30){for(let i=0;i<n;i++){const x=document.createElement('i');x.className='confetti';x.style.left=Math.random()*100+'vw';x.style.background=`hsl(${Math.random()*360} 90% 60%)`;x.style.setProperty('--x',(-100+Math.random()*200)+'px');document.body.appendChild(x);setTimeout(()=>x.remove(),1700)}}
function renderHome(){
 $('#difficultyGrid').innerHTML=Object.entries(diffs).map(([id,d])=>`<button class="difficulty-btn ${S.difficulty===id?'selected':''}" data-d="${id}"><strong>${d.label}</strong><small>${d.desc}</small></button>`).join('');
 $$('.difficulty-btn').forEach(b=>b.onclick=()=>{S.difficulty=b.dataset.d;renderHome()});
 $('#charGrid').innerHTML=chars.map(c=>`<button class="char ${S.selected===c.id?'selected':''}" data-c="${c.id}"><div class="cube" style="background:${c.css}">•ᴗ•</div><strong>${c.name}</strong><small>${c.quote}</small></button>`).join('');
 $$('.char').forEach(b=>b.onclick=()=>{S.selected=b.dataset.c;renderHome()});
}
renderHome();
$('#soundBtn').onclick=()=>{S.sound=!S.sound;$('#soundBtn').textContent=S.sound?'🔊':'🔇'};
$$('.event').forEach(b=>b.onclick=()=>openGame(b.dataset.event));
$('#randomBtn').onclick=()=>openGame(['sprint','jump','reaction'][Math.floor(Math.random()*3)]);
$('#backBtn').onclick=goHome;$('#homeBtn').onclick=goHome;$('#retryBtn').onclick=()=>{closeResult();openGame(S.event)};
function goHome(){destroyGame();closeResult();$('#gameScreen').style.display='none';$('#homeScreen').style.display='block'}
function destroyGame(){if(S.game){S.game.destroy(true);S.game=null;S.scene=null}$('#phaserMount').innerHTML=''}
function closeResult(){$('#resultPanel').style.display='none'}
function setHud(a,b,c,d){$('#hudLabel').textContent=a;$('#hudMain').textContent=b;$('#hudRightLabel').textContent=c;$('#hudRight').textContent=d;$('#hudBar').style.width=(parseFloat(d)||0)+'%'}
function setFootControls(jump=false){
 $('#controls').innerHTML=`<div class="foot-controls"><button id="leftBtn" class="tap">👈 왼발</button><button id="rightBtn" class="tap">오른발 👉</button></div>${jump?'<button id="jumpBtn" class="jump-btn" disabled>JUMP!</button>':''}`;
 $('#leftBtn').onclick=()=>foot('L');$('#rightBtn').onclick=()=>foot('R');if(jump)$('#jumpBtn').onclick=()=>S.scene?.takeoff();paintFoot('L');
}
function paintFoot(next){['leftBtn','rightBtn'].forEach(id=>$('#'+id)?.classList.remove('next'));if(next&&!S.locked)$('#'+(next==='L'?'leftBtn':'rightBtn'))?.classList.add('next')}
function foot(f){if(!S.scene||S.locked||!['run','approach'].includes(S.phase))return;if(S.lastFoot===f){S.scene.stumble?.();return}S.lastFoot=f;S.combo++;S.power=Math.min(100,S.power+4.2+Math.min(2.4,S.combo*.08));paintFoot(f==='L'?'R':'L');setHud('COMBO',S.combo,'SPEED',Math.round(S.power)+'%');S.scene.onStep?.(f)}
function showResults(title,big,rows,win){S.results=rows;$('#resultTitle').textContent=title;$('#recordBig').textContent=big;$('#resultList').innerHTML=rows.map((r,i)=>`<div class="result-row ${r.me?'me':''}"><span><strong>${i+1}위</strong> · ${r.name}</span><strong>${r.value}</strong></div>`).join('');$('#resultPanel').style.display='flex';if(win){confetti();beep(760,.12);setTimeout(()=>beep(980,.15),110)}}
function makeNemo(scene,c,x,y,label=''){const ct=scene.add.container(x,y);const shadow=scene.add.ellipse(0,c.h*.55+10,c.w*.82,13,0x000000,.22);const body=scene.add.rectangle(0,0,c.w,c.h,c.color).setStrokeStyle(2,0xffffff,.35);const face=scene.add.text(0,-2,'•ᴗ•',{fontFamily:'Arial',fontSize:'15px',fontStyle:'bold',color:'#20242d'}).setOrigin(.5);const armL=scene.add.rectangle(-c.w/2-6,4,15,6,c.color).setOrigin(.5);const armR=scene.add.rectangle(c.w/2+6,4,15,6,c.color).setOrigin(.5);const legL=scene.add.rectangle(-12,c.h/2+8,8,20,0x3c3131).setOrigin(.5,0);const legR=scene.add.rectangle(12,c.h/2+8,8,20,0x3c3131).setOrigin(.5,0);ct.add([shadow,armL,armR,legL,legR,body,face]);ct.setData({body,face,armL,armR,legL,legR,c,baseY:y});if(label){const t=scene.add.text(0,-c.h/2-20,label,{fontFamily:'Arial',fontSize:'12px',fontStyle:'bold',color:'#ffffff',backgroundColor:'#111827cc',padding:{x:6,y:3}}).setOrigin(.5);ct.add(t)}return ct}
function animateRun(nemo,t,speed=1){if(!nemo)return;const d=nemo.getData();const s=Math.sin(t*.018*speed);d.legL.rotation=s*.75;d.legR.rotation=-s*.75;d.armL.rotation=-s*.55;d.armR.rotation=s*.55;nemo.y=d.baseY+Math.abs(s)*1.8}
function stadium(scene,w=900,h=520,worldW=900){scene.cameras.main.setBackgroundColor('#7bc7ff');scene.add.rectangle(worldW/2,95,worldW,190,0x83c8f4);scene.add.rectangle(worldW/2,194,worldW,58,0x27334c);for(let x=12;x<worldW;x+=18){const col=[0xffd84d,0xff765f,0x63e6ad,0xffffff][Math.floor(Math.random()*4)];scene.add.circle(x+Math.random()*7,180+Math.random()*34,3,col,.72)}scene.add.rectangle(worldW/2,228,worldW,10,0xf2d8a5);}
function openGame(type){destroyGame();closeResult();S.event=type;S.combo=0;S.power=0;S.lastFoot=null;S.locked=false;S.phase='idle';$('#homeScreen').style.display='none';$('#gameScreen').style.display='block';const meta={sprint:['50m 네모 달리기','왼발·오른발을 번갈아 눌러서 결승선까지!'],jump:['멀리뛰기','도움닫기 후 구름판 직전에 JUMP! 선을 넘으면 파울.'],reaction:['스타트 대결','총소리 전에 누르면 부정출발! GO 순간을 노려.']}[type];$('#gameTitle').textContent=meta[0];$('#hint').textContent=meta[1];$('#roundLabel').textContent=`AI ${diffs[S.difficulty].label} · GAME ENGINE 0.4`;$('#timer').textContent='READY';const sceneClass=type==='sprint'?SprintScene:type==='jump'?JumpScene:ReactionScene;S.game=new Phaser.Game({type:Phaser.AUTO,parent:'phaserMount',width:900,height:506,backgroundColor:'#111827',physics:{default:'arcade',arcade:{gravity:{y:0},debug:false}},scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH},scene:sceneClass});}
class SprintScene extends Phaser.Scene{
 constructor(){super('Sprint')}
 create(){S.scene=this;S.phase='count';stadium(this);this.add.rectangle(450,365,900,275,0xc96443);for(let i=0;i<5;i++)this.add.rectangle(450,280+i*55,900,2,0xffffff,.35);this.add.rectangle(792,365,10,275,0xffffff);for(let y=244;y<490;y+=20)this.add.rectangle(792,y,10,10,(y/20)%2?0x111111:0xffffff);this.runners=[];const others=chars.filter(c=>c.id!==S.selected).sort(()=>Math.random()-.5).slice(0,3);const roster=[ch(),...others];for(let i=0;i<4;i++){const n=makeNemo(this,roster[i],95,275+i*55,i===0?'나':['민수','지현','철수'][i-1]);this.runners.push({n,x:95,finish:null,rate:(.78+Math.random()*.16)*diffs[S.difficulty].bot,char:roster[i],name:i===0?'나':['민수','지현','철수'][i-1]})}setFootControls(false);$('#leftBtn').disabled=$('#rightBtn').disabled=true;setHud('COMBO','0','SPEED','0%');this.count=3;$('#timer').textContent='3';call('3');beep(430);this.cd=this.time.addEvent({delay:650,repeat:2,callback:()=>{this.count--;if(this.count>0){$('#timer').textContent=this.count;call(String(this.count));beep(430)}else{S.phase='run';$('#timer').textContent='GO!';call('GO!',600);beep(780,.1);vibrate(40);$('#leftBtn').disabled=$('#rightBtn').disabled=false;paintFoot('L')}}});}
 onStep(){if(S.phase!=='run')return;const r=this.runners[0];const step=10+S.power*.055+Math.min(3,S.combo*.07);r.x=Math.min(792,r.x+step);r.n.x=r.x;if(r.x>=792)this.finishRunner(0)}
 stumble(){if(S.locked||S.phase!=='run')return;S.locked=true;S.combo=0;S.power=Math.max(0,S.power-28);setHud('COMBO','0','SPEED',Math.round(S.power)+'%');paintFoot(null);const n=this.runners[0].n;n.getData().face.setText('×﹏×');this.tweens.add({targets:n,angle:75,duration:140,yoyo:true});this.cameras.main.shake(180,.008);call('발 꼬임! 🤦');beep(140,.12,'sawtooth');vibrate([30,25,60]);setTimeout(()=>{S.locked=false;S.lastFoot=null;n.angle=0;n.getData().face.setText('•ᴗ•');paintFoot('L')},430)}
 finishRunner(i){const r=this.runners[i];if(r.finish)return;r.finish=this.time.now;if(i===0){S.phase='done';$('#leftBtn').disabled=$('#rightBtn').disabled=true;vibrate([25,30,45]);call('FINISH!',700);beep(880,.13);this.time.delayedCall(800,()=>this.finishRace())}}
 finishRace(){const meTime=this.runners[0].finish||this.time.now;this.runners.forEach((r,i)=>{if(!r.finish)r.finish=meTime+(r.x<792?(792-r.x)*8:0)});const sorted=[...this.runners].sort((a,b)=>a.finish-b.finish);const rows=sorted.map((r,i)=>({name:r.name,me:r.name==='나',value:(4.9+(r.finish-(sorted[0].finish))*0.001).toFixed(2)+'s'}));const rank=sorted.findIndex(r=>r.name==='나')+1;showResults(rank===1?'🏆 네모 스프린트 우승!':`${rank}위! 다음 판은 잡는다`,rows.find(r=>r.me).value,rows,rank===1)}
 update(time){if(S.phase==='run'){this.runners.forEach((r,i)=>{animateRun(r.n,time,1+r.rate);if(i>0&&!r.finish){if(Math.random()<diffs[S.difficulty].stumble*.015){r.n.angle=55;this.time.delayedCall(160,()=>r.n.angle=0);return}r.x+=.65+r.rate*.68;r.n.x=r.x;if(r.x>=792)this.finishRunner(i)}})}}
}
class JumpScene extends Phaser.Scene{
 constructor(){super('Jump')}
 create(){S.scene=this;S.phase='approach';S.combo=0;S.power=0;S.lastFoot=null;this.worldW=2050;stadium(this,900,506,this.worldW);this.runY=360;this.boardX=1050;this.pitStart=1090;this.pitEnd=1800;this.add.rectangle(560,395,1120,250,0xb95a3e);this.add.rectangle((this.pitStart+this.pitEnd)/2,405,this.pitEnd-this.pitStart,210,0xe7c887);this.add.rectangle(this.boardX,367,16,64,0xffffff);this.add.rectangle(this.boardX+11,367,6,64,0xe54545);for(let x=170;x<1000;x+=140){this.add.text(x,420,Math.round((this.boardX-x)/90)+'m',{fontSize:'12px',color:'#ffffff99'})}this.add.text(this.boardX-45,315,'구름판',{fontSize:'13px',fontStyle:'bold',color:'#ffffff'});this.add.text(this.pitStart+20,330,'SAND PIT',{fontSize:'18px',fontStyle:'bold',color:'#8a6731'});this.aiScores=this.makeAiScores();this.aiScores.forEach((v,i)=>{const x=this.boardX+v*90;this.add.rectangle(x,375,3,62,[0xff6570,0x64e6ad,0xffd84d][i]);this.add.text(x-18,338,['민수','지현','철수'][i],{fontSize:'10px',color:'#1e293b'})});this.player=makeNemo(this,ch(),120,this.runY,'나');this.cameras.main.setBounds(0,0,this.worldW,506);this.cameras.main.startFollow(this.player,true,.08,.08,-220,0);this.cameras.main.setDeadzone(340,350);setFootControls(true);setHud('COMBO','0','SPEED','0%');$('#timer').textContent='RUN';$('#jumpBtn').disabled=true;call('도움닫기 시작!');this.vx=0;this.vy=0;this.takeoffX=0;this.landed=false}
 makeAiScores(){const [a,b]=diffs[S.difficulty].jump;return Array.from({length:3},()=>a+Math.random()*(b-a)).sort((x,y)=>y-x)}
 onStep(){if(S.phase!=='approach')return;const step=8.5+S.power*.075+Math.min(3.5,S.combo*.06);this.player.x+=step;const remain=this.boardX-this.player.x;$('#timer').textContent=remain>0?Math.max(0,remain/90).toFixed(1)+'m':'BOARD';if(remain<190){$('#jumpBtn').disabled=false;$('#jumpBtn').textContent=remain>25?'JUMP!':remain>=-8?'JUMP! PERFECT ZONE':'늦었다!';if(remain<70)call('지금! 구름판!',350)}if(this.player.x>this.boardX+18)this.foul('선을 밟고 지나쳤다!')}
 stumble(){if(S.locked||S.phase!=='approach')return;S.locked=true;S.combo=0;S.power=Math.max(0,S.power-25);paintFoot(null);setHud('COMBO','0','SPEED',Math.round(S.power)+'%');this.player.getData().face.setText('×﹏×');this.tweens.add({targets:this.player,angle:70,x:this.player.x-9,duration:160,yoyo:true});this.cameras.main.shake(170,.008);call('도움닫기 중 발 꼬임!');vibrate([30,25,55]);beep(145,.11,'sawtooth');setTimeout(()=>{S.locked=false;S.lastFoot=null;this.player.angle=0;this.player.getData().face.setText('•ᴗ•');paintFoot('L')},420)}
 takeoff(){if(S.phase!=='approach')return;const error=this.boardX-this.player.x;if(error<-12){this.foul('구름판 선을 넘었다!');return}S.phase='air';$('#leftBtn').disabled=$('#rightBtn').disabled=$('#jumpBtn').disabled=true;this.takeoffX=this.player.x;const accuracy=Math.max(.78,1-Math.abs(Math.max(0,error-4))/310);const perfect=Math.abs(error)<=16;if(perfect){call('PERFECT TAKEOFF! 🔥',850);beep(900,.1);vibrate([20,20,35])}else call(error>70?'조금 일렀다!':'좋아! 날아간다!',700);this.vx=(390+S.power*2.15)*accuracy;this.vy=-(500+S.power*1.65);this.player.getData().face.setText('•O•');$('#timer').textContent=perfect?'PERFECT':'AIR'}
 foul(msg){if(S.phase==='foul'||S.phase==='done')return;S.phase='foul';['leftBtn','rightBtn','jumpBtn'].forEach(id=>{if($('#'+id))$('#'+id).disabled=true});this.player.getData().face.setText('×﹏×');call('FOUL! 😵',900);$('#timer').textContent='FOUL';beep(130,.2,'sawtooth');vibrate([70,40,70]);this.time.delayedCall(900,()=>this.finishJump(true,msg))}
 finishJump(foul=false,msg=''){if(S.phase==='done')return;S.phase='done';let record=foul?0:Math.max(0,(this.player.x-this.boardX)/90);record=Math.min(9.45,record);const all=[{name:'나',me:true,score:record,foul},...this.aiScores.map((v,i)=>({name:['민수','지현','철수'][i],me:false,score:v,foul:false}))].sort((a,b)=>b.score-a.score);const rows=all.map(r=>({name:r.name,me:r.me,value:r.foul?'FOUL':r.score.toFixed(2)+'m'}));const rank=all.findIndex(r=>r.me)+1;showResults(foul?'😵 파울! 구름판을 노려봐':rank===1?'🏆 멀리뛰기 우승!':`${rank}위! 기록은 ${record.toFixed(2)}m`,foul?'FOUL':record.toFixed(2)+'m',rows,rank===1&&!foul);if(msg)$('#hint').textContent=msg}
 update(time,delta){if(S.phase==='approach')animateRun(this.player,time,1+S.power/60);if(S.phase==='air'){const dt=delta/1000;this.player.x+=this.vx*dt;this.player.y+=this.vy*dt;this.vy+=1050*dt;this.player.angle+=120*dt;const meters=Math.max(0,(this.player.x-this.boardX)/90);$('#timer').textContent=meters.toFixed(2)+'m';if(this.player.y>=this.runY+35&&this.player.x>this.pitStart){this.player.y=this.runY+35;this.player.angle=0;this.player.getData().face.setText('×ᴗ×');S.phase='land';this.cameras.main.shake(220,.007);vibrate([35,20,50]);beep(110,.08,'triangle');call('푹! 착지!',650);for(let i=0;i<14;i++){const p=this.add.circle(this.player.x-10+Math.random()*35,this.player.y+20,3+Math.random()*4,0xd3ad68,.8);this.tweens.add({targets:p,x:p.x-50+Math.random()*100,y:p.y-20-Math.random()*60,alpha:0,duration:500,onComplete:()=>p.destroy()})}this.tweens.add({targets:this.player,x:this.player.x+35,angle:65,duration:250,yoyo:true,onComplete:()=>{this.player.angle=0;this.finishJump(false)}})}}}
}
class ReactionScene extends Phaser.Scene{
 constructor(){super('Reaction')}
 create(){S.scene=this;S.phase='ready';stadium(this);this.add.rectangle(450,390,900,230,0xc45f41);for(let i=0;i<5;i++)this.add.rectangle(450,300+i*48,900,2,0xffffff,.3);const others=chars.filter(c=>c.id!==S.selected).sort(()=>Math.random()-.5).slice(0,3),roster=[ch(),...others];this.runners=roster.map((c,i)=>({n:makeNemo(this,c,220,300+i*48,i===0?'나':['민수','지현','철수'][i-1]),name:i===0?'나':['민수','지현','철수'][i-1],reaction:null}));$('#controls').innerHTML='<button id="reactionBtn" class="reaction-btn">READY…</button>';setHud('상태','집중','AI',diffs[S.difficulty].label);$('#timer').textContent='READY';const b=$('#reactionBtn');b.onclick=()=>this.press();this.goAt=0;const wait=1500+Math.random()*2400;this.time.delayedCall(wait,()=>{if(S.phase!=='ready')return;S.phase='go';this.goAt=performance.now();b.textContent='GO!';b.classList.add('go');$('#timer').textContent='GO!';call('탕! GO!',550);beep(950,.08);vibrate(30);const [lo,hi]=diffs[S.difficulty].reaction;this.runners.slice(1).forEach(r=>r.reaction=lo+Math.random()*(hi-lo))})}
 press(){const b=$('#reactionBtn');if(S.phase==='ready'){S.phase='false';b.textContent='부정출발!';b.classList.add('false');$('#timer').textContent='FALSE';call('너무 빨랐다! 😵');beep(120,.2,'sawtooth');vibrate([70,40,70]);const [lo,hi]=diffs[S.difficulty].reaction;this.runners[0].reaction=9999;this.runners.slice(1).forEach(r=>r.reaction=lo+Math.random()*(hi-lo));this.time.delayedCall(900,()=>this.finish())}else if(S.phase==='go'){S.phase='done';this.runners[0].reaction=performance.now()-this.goAt;b.textContent=Math.round(this.runners[0].reaction)+'ms';this.runAway();this.time.delayedCall(900,()=>this.finish())}}
 runAway(){this.runners.forEach(r=>{const delay=Math.min(700,r.reaction);this.time.delayedCall(delay,()=>this.tweens.add({targets:r.n,x:610,duration:520,ease:'Quad.easeIn'}))})}
 finish(){const sorted=[...this.runners].sort((a,b)=>a.reaction-b.reaction);const rows=sorted.map(r=>({name:r.name,me:r.name==='나',value:r.reaction>9000?'실격':Math.round(r.reaction)+'ms'}));const rank=sorted.findIndex(r=>r.name==='나')+1;showResults(this.runners[0].reaction>9000?'😵 부정출발!':rank===1?'⚡ 스타트 왕!':`${rank}위!`,this.runners[0].reaction>9000?'FALSE':Math.round(this.runners[0].reaction)+'ms',rows,rank===1)}
 update(time){if(['go','done'].includes(S.phase))this.runners.forEach(r=>animateRun(r.n,time,1.4))}
}