const characters = [
  {id:"sugar", name:"각설탕", cls:"sugar", quote:"달지만 승부는 쓰다"},
  {id:"brown", name:"흑설탕", cls:"brown", quote:"묵직하게 간다"},
  {id:"salt", name:"소금덩어리", cls:"salt", quote:"지는 건 짜다"},
  {id:"tofu", name:"두부", cls:"tofu", quote:"부서져도 달린다"},
  {id:"brick", name:"벽돌", cls:"brick", quote:"대화보다 돌진"},
  {id:"box", name:"택배상자", cls:"box", quote:"내용물은 비밀"},
  {id:"apartment", name:"아파트", cls:"apartment", quote:"관리비 걸고 뛴다"},
  {id:"gold", name:"금괴", cls:"gold", quote:"몸값부터 다름"},
  {id:"safe", name:"금고", cls:"safe", quote:"마음은 잠금"}
];

const difficultyConfig = {
  easy:{label:"느긋",botRate:[190,230],step:[1.15,1.55],stumble:.13,reaction:[330,620],jump:[4.6,7.1]},
  normal:{label:"보통",botRate:[155,195],step:[1.35,1.75],stumble:.075,reaction:[230,480],jump:[5.2,7.8]},
  hard:{label:"빡셈",botRate:[125,165],step:[1.5,1.95],stumble:.045,reaction:[175,350],jump:[5.8,8.25]},
  hell:{label:"악마",botRate:[100,138],step:[1.7,2.15],stumble:.022,reaction:[135,285],jump:[6.3,8.55]}
};

const state={selected:"sugar",difficulty:"normal",event:"sprint",players:[],running:false,timers:[],lastFoot:null,distance:0,combo:0,speedPower:0,locked:false,finishTime:null,startTime:null,speed:0,jumpMarker:0,jumpDir:1,jumpPhase:"charge",reactionReady:false,reactionGoAt:0,sound:true};
const $=q=>document.querySelector(q);const $$=q=>[...document.querySelectorAll(q)];
const screens={home:$("#homeScreen"),game:$("#gameScreen"),result:$("#resultScreen")};
function showScreen(name){Object.values(screens).forEach(x=>x.classList.remove("active"));screens[name].classList.add("active");document.body.classList.toggle("game-mode",name==="game")}
function toast(msg){const t=$("#toast");t.textContent=msg;t.classList.add("show");clearTimeout(t._h);t._h=setTimeout(()=>t.classList.remove("show"),1000)}
function vibrate(pattern){if(navigator.vibrate)navigator.vibrate(pattern)}
let audioCtx=null;
function tone(freq=440,dur=.08,type="square",vol=.035){if(!state.sound)return;try{audioCtx=audioCtx||new (window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.value=vol;o.connect(g);g.connect(audioCtx.destination);o.start();g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+dur);o.stop(audioCtx.currentTime+dur)}catch(e){}}
function sfx(name){if(name==="count")tone(430,.07,"square",.03);if(name==="go"){tone(720,.12,"square",.045);setTimeout(()=>tone(930,.11,"square",.035),80)}if(name==="step")tone(105,.025,"triangle",.012);if(name==="stumble"){tone(170,.09,"sawtooth",.04);setTimeout(()=>tone(90,.12,"sawtooth",.025),55)}if(name==="finish"){tone(660,.12,"square",.04);setTimeout(()=>tone(880,.12,"square",.04),100);setTimeout(()=>tone(1100,.18,"square",.04),200)}}
function raceCall(text,ms=900){const el=$("#raceCall");if(!el)return;el.textContent=text;el.classList.remove("hidden");clearTimeout(el._h);el._h=setTimeout(()=>el.classList.add("hidden"),ms)}
function pulseCountdown(text){const el=$("#countdownOverlay");if(!el)return;el.textContent=text;el.classList.remove("show");void el.offsetWidth;el.classList.add("show")}
function setRunnerFace(i,face){const f=$("#runner"+i)?.querySelector(".face");if(f)f.textContent=face}
function screenShake(){const a=$("#arena");if(!a)return;a.classList.remove("shake");void a.offsetWidth;a.classList.add("shake");setTimeout(()=>a.classList.remove("shake"),260)}
function confettiBurst(count=26){for(let i=0;i<count;i++){const c=document.createElement("i");c.className="confetti";c.style.left=(Math.random()*100)+"vw";c.style.background=`hsl(${Math.random()*360} 85% 60%)`;c.style.setProperty("--drift",`${-80+Math.random()*160}px`);c.style.animationDelay=(Math.random()*.25)+"s";document.body.appendChild(c);setTimeout(()=>c.remove(),2000)}}
function nemoHTML(c,face="•ᴗ•"){return `<div class="nemo ${c.cls}"><span class="face">${face}</span><i class="arm l"></i><i class="arm r"></i><i class="leg l"></i><i class="leg r"></i></div>`}
function clearTimers(){state.timers.forEach(t=>{clearTimeout(t);clearInterval(t)});state.timers=[]}

function renderCharacters(){
  $("#characterGrid").innerHTML=characters.map(c=>`<button class="char-card ${state.selected===c.id?"selected":""}" data-char="${c.id}"><div class="mini-char">${nemoHTML(c)}</div><strong>${c.name}</strong><small>${c.quote}</small></button>`).join("");
  $$(".char-card").forEach(btn=>btn.onclick=()=>{state.selected=btn.dataset.char;renderCharacters();toast(`${characters.find(c=>c.id===state.selected).name} 선택!`)})
}
function renderDifficulty(){
  $$(".difficulty-btn").forEach(btn=>{btn.classList.toggle("selected",btn.dataset.difficulty===state.difficulty);btn.onclick=()=>{state.difficulty=btn.dataset.difficulty;renderDifficulty();toast(`AI ${difficultyConfig[state.difficulty].label}`)}})
}
renderCharacters();renderDifficulty();

const eventMeta={sprint:{title:"50m 네모 달리기",hint:"왼발·오른발을 정확히 번갈아! 콤보가 쌓이면 가속한다."},reaction:{title:"반응속도",hint:"READY 중에 누르면 실격! 초록색 GO!가 뜨는 순간 눌러."},jump:{title:"멀리뛰기",hint:"RUN을 연타해 속도를 채운 뒤 JUMP 타이밍을 맞춰!"}};
function buildPlayers(){const mine=characters.find(c=>c.id===state.selected);const pool=characters.filter(c=>c.id!==mine.id).sort(()=>Math.random()-.5).slice(0,3);state.players=[{name:"나",char:mine,me:true,score:0},...pool.map((c,i)=>({name:["민수","지현","철수"][i],char:c,me:false,score:0}))]}
function startEvent(type){clearTimers();state.event=type;buildPlayers();state.running=false;$("#gameTitle").textContent=eventMeta[type].title;$("#gameHint").textContent=eventMeta[type].hint;$("#roundLabel").textContent=`네모 운동회 · AI ${difficultyConfig[state.difficulty].label}`;$("#timer").textContent="READY";$("#sprintHud").classList.toggle("hidden",type!=="sprint");showScreen("game");if(type==="sprint")setupSprint();if(type==="reaction")setupReaction();if(type==="jump")setupJump()}
$$(".event-card").forEach(b=>b.onclick=()=>startEvent(b.dataset.event));
$("#randomBtn").onclick=()=>{const keys=Object.keys(eventMeta);startEvent(keys[Math.floor(Math.random()*keys.length)])};
$("#backBtn").onclick=()=>{clearTimers();showScreen("home")};

function setupSprint(){
  Object.assign(state,{lastFoot:null,distance:0,combo:0,speedPower:0,locked:false,finishTime:null,startTime:null});updateSprintHud();$("#arena").classList.remove("rush");
  $("#arena").className="arena sprint-arena";
  $("#arena").innerHTML=`<div class="stadium-bg"><div class="crowd"></div></div><div class="scoreboard">NEMO 50M</div><div class="track-gloss"></div><div class="start-line"></div><div class="finish-line"></div><div class="finish-banner">FINISH</div><div class="meter-mark" style="left:29%"><span>15m</span></div><div class="meter-mark" style="left:49%"><span>25m</span></div><div class="meter-mark" style="left:69%"><span>40m</span></div><div class="speed-lines"><i style="top:10%"></i><i></i><i></i><i></i></div><div id="countdownOverlay" class="countdown-overlay">3</div>`+state.players.map((p,i)=>`<div class="lane" style="top:${38+i*15}%"></div><div id="runner${i}" class="runner ${i===0?"me-runner":""}" style="top:${35+i*15}%">${nemoHTML(p.char,i===0?"•̀ᴗ•́":"•ᴗ•")}<span class="name-tag">${p.name} · ${p.char.name}</span></div>`).join("");
  $("#gameControls").innerHTML=`<div class="foot-controls"><button id="leftFoot" class="tap-btn">👈 왼발</button><button id="rightFoot" class="tap-btn">오른발 👉</button></div>`;
  $("#leftFoot").disabled=true;$("#rightFoot").disabled=true;let count=3;$("#timer").textContent=count;pulseCountdown("3");sfx("count");raceCall("집중... 발 순서 틀리면 바로 넘어진다",1300);
  const cd=setInterval(()=>{count--;if(count>0){$("#timer").textContent=count;pulseCountdown(String(count));sfx("count");return}clearInterval(cd);state.running=true;state.startTime=performance.now();$("#timer").textContent="GO!";pulseCountdown("GO!");sfx("go");raceCall("GO! GO! GO!",700);$("#leftFoot").disabled=false;$("#rightFoot").disabled=false;paintNextFoot("L");vibrate(45);state.players.forEach((p,i)=>$("#runner"+i).classList.add("running"));sprintBots();const end=setTimeout(()=>finishSprint(true),11000);state.timers.push(end);let remain=11;const clock=setInterval(()=>{remain--;$("#timer").textContent=remain>0?remain+"s":"끝!";if(remain<=0)clearInterval(clock)},1000);state.timers.push(clock)},650);state.timers.push(cd);
  const hit=foot=>{if(!state.running||state.locked)return;if(state.lastFoot===foot){stumblePlayer();return}state.lastFoot=foot;state.combo++;state.speedPower=Math.min(100,state.speedPower+4.2+Math.min(3,state.combo*.08));const boost=2.0+(state.speedPower/100)*1.3+Math.min(.65,state.combo*.018);state.distance=Math.min(100,state.distance+boost);updateRunner(0,state.distance);updateSprintHud();paintNextFoot(foot==="L"?"R":"L");dustAt(0);if(state.combo%3===0)sfx("step");if(state.combo===10){raceCall("10 COMBO 🔥 가속 시작!",900);vibrate(25)}if(state.combo===20){raceCall("20 COMBO ⚡ 네모 폭주!",1000);vibrate([25,20,25])}if(state.speedPower>=88&&state.combo===26)raceCall("MAX SPEED!!!",850);if(state.distance>=100)finishSprint(false)};
  $("#leftFoot").onclick=()=>hit("L");$("#rightFoot").onclick=()=>hit("R")
}
function paintNextFoot(next){["leftFoot","rightFoot"].forEach(id=>$("#"+id)?.classList.remove("next-foot"));if(state.running&&!state.locked&&next)$("#"+(next==="L"?"leftFoot":"rightFoot"))?.classList.add("next-foot")}
function updateSprintHud(){$("#comboValue").textContent=state.combo;$("#speedFillRace").style.width=state.speedPower+"%";const tier=state.speedPower<30?"1단":state.speedPower<62?"2단":state.speedPower<88?"3단":"MAX";$("#speedTier").textContent=tier;const r=$("#runner0");if(r){r.classList.toggle("fast",state.speedPower>=45);r.classList.toggle("blazing",state.speedPower>=80)}$("#arena")?.classList.toggle("rush",state.speedPower>=80)}
function runnerPop(i,text){const r=$("#runner"+i);if(!r)return;const s=document.createElement("span");s.className="status-pop";s.textContent=text;r.appendChild(s);setTimeout(()=>s.remove(),750)}
function dustAt(i){const r=$("#runner"+i),arena=$("#arena");if(!r||!arena)return;const d=document.createElement("i");d.className="dust";d.style.left=(r.offsetLeft+8)+"px";d.style.top=(r.offsetTop+56)+"px";arena.appendChild(d);setTimeout(()=>d.remove(),500)}
function stumblePlayer(){state.locked=true;state.combo=0;state.speedPower=Math.max(0,state.speedPower-28);state.distance=Math.max(0,state.distance-1.3);updateRunner(0,state.distance);updateSprintHud();paintNextFoot(null);const r=$("#runner0");r?.classList.add("stumble");setRunnerFace(0,"×﹏×");runnerPop(0,"발 꼬임!");raceCall("으악! 발 꼬였다 🤦",760);screenShake();sfx("stumble");vibrate([30,30,65]);$("#leftFoot").classList.add("locked");$("#rightFoot").classList.add("locked");const t=setTimeout(()=>{state.locked=false;r?.classList.remove("stumble");setRunnerFace(0,"•̀ᴗ•́");$("#leftFoot").classList.remove("locked");$("#rightFoot").classList.remove("locked");state.lastFoot=null;paintNextFoot("L")},480);state.timers.push(t)}
function sprintBots(){const cfg=difficultyConfig[state.difficulty];state.players.slice(1).forEach((p,idx)=>{let d=0,power=Math.random()*12;const baseStep=cfg.step[0]+Math.random()*(cfg.step[1]-cfg.step[0]);const rate=cfg.botRate[0]+Math.random()*(cfg.botRate[1]-cfg.botRate[0]);const loop=setInterval(()=>{if(!state.running){clearInterval(loop);return}if(Math.random()<cfg.stumble){power=Math.max(0,power-22);d=Math.max(0,d-.8);p.botDistance=d;const ri=idx+1;$("#runner"+ri)?.classList.add("stumble");setRunnerFace(ri,"×﹏×");runnerPop(ri,"삐끗!");const tt=setTimeout(()=>{$("#runner"+ri)?.classList.remove("stumble");setRunnerFace(ri,"•ᴗ•")},420);state.timers.push(tt);return}power=Math.min(100,power+2.4+Math.random()*2);d+=baseStep*(.82+Math.random()*.32)*(1+power/250);p.botDistance=Math.min(100,d);updateRunner(idx+1,p.botDistance);dustAt(idx+1);const rr=$("#runner"+(idx+1));rr?.classList.toggle("fast",power>55);rr?.classList.toggle("blazing",power>88);if(p.botDistance>=100){p.finishTime=performance.now()-state.startTime;clearInterval(loop);rr?.classList.add("finish-pop");checkSprintFinish()}},rate);state.timers.push(loop)})}
function updateRunner(i,d){const el=$("#runner"+i);if(el)el.style.left=(5+d*.78)+"%"}
function checkSprintFinish(){if(!state.running)return;const done=state.players.every((p,i)=>i===0?state.distance>=100:(p.botDistance||0)>=100);if(done)finishSprint(true)}
function finishSprint(force){if(!state.running)return;if(state.distance>=100&&!state.finishTime){state.finishTime=performance.now()-state.startTime;$("#runner0")?.classList.add("finish-pop");setRunnerFace(0,"⌐■ᴗ■");raceCall(`FINISH! ${(state.finishTime/1000).toFixed(2)}초`,1200);sfx("finish");confettiBurst(18);vibrate(80)}if(!force){state.locked=true;$("#leftFoot").disabled=true;$("#rightFoot").disabled=true;const t=setTimeout(()=>finishSprint(true),1200);state.timers.push(t);return}state.running=false;clearTimers();state.players[0].score=state.finishTime?100000-state.finishTime:state.distance;state.players[0].display=state.finishTime?`${(state.finishTime/1000).toFixed(2)}초`:`${(state.distance/2).toFixed(1)}m`;state.players.slice(1).forEach(p=>{p.score=p.finishTime?100000-p.finishTime:(p.botDistance||0);p.display=p.finishTime?`${(p.finishTime/1000).toFixed(2)}초`:`${((p.botDistance||0)/2).toFixed(1)}m`});setTimeout(()=>showResults("기록",v=>v,true,p=>p.display),500)}

function setupReaction(){
  $("#sprintHud").classList.add("hidden");$("#arena").className="arena";$("#raceCall").classList.add("hidden");$("#arena").innerHTML=`<div style="position:absolute;inset:0;display:grid;place-items:center;padding:20px"><div style="display:flex;gap:10px;align-items:flex-end">${state.players.map((p,i)=>`<div style="text-align:center">${nemoHTML(p.char,i===0?"•̀_•́":"•_•")}<small style="display:block;margin-top:8px">${p.name}</small></div>`).join("")}</div></div>`;$("#gameControls").innerHTML=`<button id="reactionBtn" class="big-tap">READY…</button>`;const b=$("#reactionBtn");state.reactionReady=true;state.reactionGoAt=0;const wait=1400+Math.random()*2600;const go=setTimeout(()=>{state.reactionGoAt=performance.now();b.textContent="GO!";b.classList.add("go");$("#timer").textContent="GO!";vibrate(35);const [lo,hi]=difficultyConfig[state.difficulty].reaction;state.players.slice(1).forEach(p=>p.score=lo+Math.random()*(hi-lo))},wait);state.timers.push(go);b.onclick=()=>{if(!state.reactionReady)return;const [lo,hi]=difficultyConfig[state.difficulty].reaction;if(!state.reactionGoAt){state.reactionReady=false;clearTimers();state.players[0].score=9999;state.players.slice(1).forEach(p=>p.score=lo+Math.random()*(hi-lo));b.textContent="실격!";b.classList.add("false");$("#timer").textContent="FALSE";vibrate([50,40,70]);setTimeout(()=>showResults("반응시간",v=>v>9000?"실격":`${Math.round(v)}ms`,false),700)}else{state.reactionReady=false;state.players[0].score=performance.now()-state.reactionGoAt;b.textContent=`${Math.round(state.players[0].score)}ms`;setTimeout(()=>showResults("반응시간",v=>`${Math.round(v)}ms`,false),600)}}
}
function setupJump(){
  $("#sprintHud").classList.add("hidden");$("#arena").className="arena";$("#raceCall").classList.add("hidden");state.speed=0;state.jumpMarker=0;state.jumpDir=1;state.jumpPhase="charge";$("#arena").innerHTML=`<div style="position:absolute;left:50%;top:48%;transform:translate(-50%,-50%);text-align:center"><div id="jumper" style="display:inline-block;transform:scale(1.45)">${nemoHTML(state.players[0].char,"•̀ᴗ•́")}</div><p style="margin-top:28px;color:#17202c;font-weight:900">속도를 최대한 끌어올려!</p></div>`;$("#gameControls").innerHTML=`<div class="speed-bar"><div id="speedFill" class="speed-fill"></div></div><button id="runBtn" class="big-tap" style="min-height:130px">RUN! RUN!</button><div id="jumpUI" style="display:none"><div class="jump-zone"><div id="jumpMarker" class="jump-marker"></div></div><button id="jumpBtn" class="tap-btn" style="width:100%;min-height:100px">JUMP!</button></div>`;$("#timer").textContent="4s";state.running=true;$("#runBtn").onclick=()=>{if(state.jumpPhase!=="charge")return;state.speed=Math.min(100,state.speed+3.8);$("#speedFill").style.width=state.speed+"%"};let remain=4;const charge=setInterval(()=>{remain--;$("#timer").textContent=remain>0?remain+"s":"JUMP";if(remain<=0){clearInterval(charge);state.jumpPhase="aim";$("#runBtn").style.display="none";$("#jumpUI").style.display="block";animateJumpMarker()}},1000);state.timers.push(charge);$("#jumpBtn").onclick=()=>finishJump()
}
function animateJumpMarker(){const loop=setInterval(()=>{if(state.jumpPhase!=="aim"){clearInterval(loop);return}state.jumpMarker+=state.jumpDir*3.2;if(state.jumpMarker>=100){state.jumpMarker=100;state.jumpDir=-1}if(state.jumpMarker<=0){state.jumpMarker=0;state.jumpDir=1}$("#jumpMarker").style.left=`calc(${state.jumpMarker}% - 4px)`},28);state.timers.push(loop)}
function finishJump(){if(state.jumpPhase!=="aim")return;state.jumpPhase="done";clearTimers();const timing=Math.max(0,100-Math.abs(50-state.jumpMarker)*2);state.players[0].score=2.5+(state.speed/100)*4.3+(timing/100)*2.1;const [lo,hi]=difficultyConfig[state.difficulty].jump;state.players.slice(1).forEach(p=>p.score=lo+Math.random()*(hi-lo));$("#jumper").style.transform=`translate(${80+timing}px,-${40+timing/2}px) rotate(${20+timing/3}deg) scale(1.45)`;$("#gameHint").textContent=`속도 ${Math.round(state.speed)}% · 타이밍 ${Math.round(timing)}%`;setTimeout(()=>showResults("기록",v=>`${v.toFixed(2)}m`,true),700)}
function showResults(label,format,higherBetter,displayFn=null){clearTimers();const sorted=[...state.players].sort((a,b)=>higherBetter?b.score-a.score:a.score-b.score);const won=sorted[0].me;$("#resultTitle").textContent=won?"🏆 네모 챔피언!":"😵 "+sorted[0].name+" 우승";$(".result-card")?.classList.toggle("celebrate",won);if(won){confettiBurst(34);sfx("finish")}if(state.event==="sprint"&&state.finishTime){const key=`nemoBest_${state.difficulty}`;const prev=Number(localStorage.getItem(key)||0);if(!prev||state.finishTime<prev){localStorage.setItem(key,String(state.finishTime));toast("🏅 개인 최고기록!")}}const top=sorted.slice(0,3),order=top.length>=3?[top[1],top[0],top[2]]:top;$("#podium").innerHTML=order.map(p=>{const realRank=sorted.indexOf(p)+1;const shown=displayFn?displayFn(p):format(p.score);return `<div class="podium-slot">${nemoHTML(p.char,realRank===1?"⌐■ᴗ■":"•ᴗ•")}<strong style="display:block;margin:8px 0">${p.name}</strong><div class="podium-box">${realRank}위<br><small>${shown}</small></div></div>`}).join("");$("#resultList").innerHTML=sorted.map((p,i)=>{const shown=displayFn?displayFn(p):format(p.score);return `<div class="result-row ${p.me?"me":""}"><span><strong>${i+1}위</strong> · ${p.name} <small style="color:var(--muted)">(${p.char.name})</small></span><strong>${shown}</strong></div>`}).join("");const myRank=sorted.findIndex(p=>p.me)+1;$("#rewardText").textContent=`🪙 ${myRank===1?30:myRank===2?20:10}`;showScreen("result")}
$("#retryBtn").onclick=()=>startEvent(state.event);$("#homeBtn").onclick=()=>showScreen("home");$("#soundBtn").onclick=()=>{state.sound=!state.sound;$("#soundBtn").textContent=state.sound?"🔊":"🔇";if(state.sound)tone(660,.08,"square",.03)};
